/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Fazer login */
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Fazer logout */
    post: operations["AuthController_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Renovar tokens de acesso */
    post: operations["AuthController_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar grupos do usuário */
    get: operations["GroupController_find"];
    put?: never;
    /** Criar um novo grupo */
    post: operations["GroupController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups/{groupId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar um grupo por ID */
    get: operations["GroupController_findOne"];
    put?: never;
    post?: never;
    /** Deletar um grupo */
    delete: operations["GroupController_delete"];
    options?: never;
    head?: never;
    /** Atualizar um grupo */
    patch: operations["GroupController_update"];
    trace?: never;
  };
  "/groups/{groupId}/invite-code": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Resetar o código de convite do grupo */
    patch: operations["GroupController_resetInviteCode"];
    trace?: never;
  };
  "/groups/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Entrar em um grupo através do código de convite */
    post: operations["GroupController_join"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups/{groupId}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar membros de um grupo */
    get: operations["GroupMemberController_find"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups/{groupId}/members/{memberId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar um membro do grupo */
    get: operations["GroupMemberController_findOne"];
    put?: never;
    post?: never;
    /** Remover um membro do grupo */
    delete: operations["GroupMemberController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups/{groupId}/members/{memberId}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Alterar o role de um membro do grupo */
    patch: operations["GroupMemberController_changeRole"];
    trace?: never;
  };
  "/quizzes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar quizzes */
    get: operations["QuizController_find"];
    put?: never;
    /** Criar um novo quiz */
    post: operations["QuizController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/quizzes/shared": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar quizzes compartilhados com o usuário */
    get: operations["QuizController_findShared"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/quizzes/{quizId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar um quiz por ID */
    get: operations["QuizController_findOne"];
    put?: never;
    post?: never;
    /** Deletar um quiz */
    delete: operations["QuizController_delete"];
    options?: never;
    head?: never;
    /** Atualizar um quiz */
    patch: operations["QuizController_update"];
    trace?: never;
  };
  "/quizzes/{quizId}/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar itens de quiz */
    get: operations["QuizItemController_find"];
    put?: never;
    /** Criar um novo item de quiz */
    post: operations["QuizItemController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/quizzes/{quizId}/items/{quizItemId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar um item de quiz por ID */
    get: operations["QuizItemController_findOne"];
    put?: never;
    post?: never;
    /** Deletar um item de quiz */
    delete: operations["QuizItemController_delete"];
    options?: never;
    head?: never;
    /**
     * Atualizar um item de quiz
     * @description Mantém as opções existentes se nenhuma for fornecida
     */
    patch: operations["QuizItemController_update"];
    trace?: never;
  };
  "/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar tarefas */
    get: operations["TaskController_find"];
    put?: never;
    /** Criar uma nova tarefa */
    post: operations["TaskController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tasks/shared": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar tarefas compartilhadas com o usuário */
    get: operations["TaskController_findShared"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tasks/{taskId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar uma tarefa por ID */
    get: operations["TaskController_findOne"];
    put?: never;
    post?: never;
    /** Deletar uma tarefa */
    delete: operations["TaskController_delete"];
    options?: never;
    head?: never;
    /** Atualizar uma tarefa */
    patch: operations["TaskController_update"];
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar usuários */
    get: operations["UserController_find"];
    put?: never;
    /** Criar um novo usuário */
    post: operations["UserController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar um usuário por ID */
    get: operations["UserController_findOne"];
    put?: never;
    post?: never;
    /** Deletar um usuário */
    delete: operations["UserController_delete"];
    options?: never;
    head?: never;
    /** Atualizar um usuário */
    patch: operations["UserController_update"];
    trace?: never;
  };
  "/whiteboards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar whiteboards */
    get: operations["WhiteboardController_find"];
    put?: never;
    /** Criar um novo whiteboard */
    post: operations["WhiteboardController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/whiteboards/shared": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar whiteboards compartilhados com o usuário */
    get: operations["WhiteboardController_findShared"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/whiteboards/{whiteboardId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buscar um whiteboard por ID */
    get: operations["WhiteboardController_findOne"];
    put?: never;
    post?: never;
    /** Deletar um whiteboard */
    delete: operations["WhiteboardController_delete"];
    options?: never;
    head?: never;
    /** Atualizar um whiteboard */
    patch: operations["WhiteboardController_update"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginBodyDTO: {
      /** @description Email */
      email: string;
      /** @description Senha */
      password: string;
    };
    LoginResponseDTO: {
      /** @description Access token */
      accessToken: string;
      /** @description Refresh token */
      refreshToken: string;
    };
    LogoutBodyDTO: {
      /** @description Refresh token */
      refreshToken: string;
    };
    RefreshTokensBodyDTO: {
      /** @description Refresh token */
      refreshToken: string;
    };
    RefreshTokensResponseDTO: {
      /** @description Novo access token */
      accessToken: string;
      /** @description Novo refresh token */
      refreshToken: string;
    };
    CreateGroupBodyDTO: {
      /**
       * @description Nome do grupo
       * @example Grupo de Estudos de Matemática
       */
      name: string;
      /**
       * @description Descrição do grupo
       * @example Grupo dedicado aos estudos de matemática avançada
       */
      description?: string;
    };
    GroupResponseDTO: {
      /**
       * @description ID único do grupo
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string;
      /**
       * @description Nome do grupo
       * @example Grupo de Estudos de Matemática
       */
      name: string;
      /**
       * @description Descrição do grupo
       * @example Grupo dedicado aos estudos de matemática avançada
       */
      description?: string;
      /**
       * @description Código de convite do grupo
       * @example ABC12345
       */
      inviteCode: string;
      /**
       * Format: date-time
       * @description Data de criação do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Data da última atualização do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      updatedAt: string;
    };
    FindGroupResponseDTO: {
      /** @description Lista de grupos */
      groups: components["schemas"]["GroupResponseDTO"][];
      /**
       * @description Total de grupos encontrados
       * @example 10
       */
      total: number;
    };
    UpdateGroupBodyDTO: {
      /**
       * @description Nome do grupo
       * @example Grupo de Estudos de Matemática
       */
      name?: string;
      /**
       * @description Descrição do grupo
       * @example Grupo dedicado aos estudos de matemática avançada
       */
      description?: string;
    };
    JoinGroupBodyDTO: {
      /**
       * @description Código de convite do grupo
       * @example ABC12345
       */
      inviteCode: string;
    };
    UserResponseDTO: {
      /**
       * @description ID único do usuário
       * @example 1
       */
      id: number;
      /**
       * @description Nome completo do usuário
       * @example João Silva
       */
      name: string;
      /**
       * @description Email do usuário
       * @example joao.silva@example.com
       */
      email: string;
      /**
       * Format: date-time
       * @description Data de nascimento do usuário
       * @example 1990-01-15T00:00:00.000Z
       */
      birthdate?: string;
      /**
       * @description Número de telefone do usuário
       * @example +55 11 98765-4321
       */
      phoneNumber?: string;
      /**
       * @description URL da foto de perfil do usuário
       * @example https://example.com/photos/user.jpg
       */
      photoUrl?: string;
      /**
       * @description Papel do usuário
       * @example user
       * @enum {string}
       */
      role: "admin" | "user";
      /**
       * Format: date-time
       * @description Data de criação do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Data da última atualização do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      updatedAt: string;
    };
    GroupMemberResponseDTO: {
      /**
       * @description ID único do membro
       * @example 1
       */
      id: number;
      /**
       * @description Role do membro no grupo
       * @example member
       * @enum {string}
       */
      role: "owner" | "admin" | "member";
      /**
       * @description ID do grupo
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      groupId: string;
      /**
       * @description ID do usuário
       * @example 1
       */
      userId: number;
      /** @description Dados do usuário */
      user?: components["schemas"]["UserResponseDTO"];
      /**
       * Format: date-time
       * @description Data de criação do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Data da última atualização do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      updatedAt: string;
    };
    FindGroupMembersResponseDTO: {
      /** @description Lista de membros do grupo */
      members: components["schemas"]["GroupMemberResponseDTO"][];
      /**
       * @description Total de membros
       * @example 10
       */
      total: number;
    };
    ChangeMemberRoleBodyDTO: {
      /**
       * @description Novo role do membro
       * @example admin
       * @enum {string}
       */
      role: "owner" | "admin" | "member";
    };
    CreateQuizBodyDTO: {
      /**
       * @description Título do quiz
       * @example Quiz de Matemática
       */
      title: string;
      /**
       * @description Descrição do quiz
       * @example Um quiz sobre matemática básica
       */
      description?: string;
    };
    QuizOptionResponseDTO: {
      /**
       * @description ID único da opção
       * @example 1
       */
      id: number;
      /**
       * @description ID do item do quiz
       * @example 1
       */
      quizItemId: number;
      /**
       * @description Texto da opção
       * @example Opção A
       */
      text: string;
      /**
       * @description Indica se a opção é a correta
       * @example true
       */
      isCorrect: boolean;
      /**
       * @description Ordem da opção
       * @example 1
       */
      position: number;
    };
    QuizItemResponseDTO: {
      /**
       * @description ID único do item
       * @example 1
       */
      id: number;
      /**
       * @description ID do quiz
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      quizId: string;
      /**
       * @description Pergunta do item
       * @example Qual é a capital do Brasil?
       */
      question: string;
      /** @description Opções de resposta */
      options?: components["schemas"]["QuizOptionResponseDTO"][];
      /**
       * @description Ordem do item no quiz
       * @example 1
       */
      position: number;
      /**
       * @description Tempo limite em segundos
       * @example 30
       */
      timeLimit?: number;
      /**
       * @description Explicação da resposta
       * @example Brasília é a capital do Brasil desde 1960.
       */
      explanation?: string;
      /**
       * Format: date-time
       * @description Data de criação do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Data da última atualização do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      updatedAt: string;
    };
    QuizResponseDTO: {
      /**
       * @description ID único do quiz
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string;
      /**
       * @description Título do quiz
       * @example Quiz de Matemática
       */
      title: string;
      /**
       * @description Descrição do quiz
       * @example Um quiz sobre matemática básica
       */
      description?: string;
      /** @description Itens do quiz */
      items?: components["schemas"]["QuizItemResponseDTO"][];
      /**
       * Format: date-time
       * @description Data de criação do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Data da última atualização do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      updatedAt: string;
    };
    FindQuizResponseDTO: {
      /** @description Lista de quizzes */
      quizzes: components["schemas"]["QuizResponseDTO"][];
      /**
       * @description Total de quizzes encontrados
       * @example 10
       */
      total: number;
    };
    UpdateQuizBodyDTO: {
      /**
       * @description Título do quiz
       * @example Quiz de Matemática
       */
      title?: string;
      /**
       * @description Descrição do quiz
       * @example Um quiz sobre matemática básica
       */
      description?: string;
    };
    CreateQuizOptionDTO: {
      /**
       * @description Texto da opção
       * @example Opção A
       */
      text: string;
      /**
       * @description Indica se a opção é a correta
       * @example true
       */
      isCorrect: boolean;
      /**
       * @description Ordem da opção
       * @example 1
       */
      position: number;
    };
    CreateQuizItemBodyDTO: {
      /**
       * @description Pergunta do item
       * @example Qual é a capital do Brasil?
       */
      question: string;
      /** @description Opções de resposta do item */
      options: components["schemas"]["CreateQuizOptionDTO"][];
      /**
       * @description Ordem do item no quiz
       * @example 1
       */
      position: number;
      /**
       * @description Tempo limite em segundos
       * @example 30
       */
      timeLimit?: number;
      /**
       * @description Explicação da resposta
       * @example Brasília é a capital do Brasil desde 1960.
       */
      explanation?: string;
    };
    FindQuizItemResponseDTO: {
      /** @description Lista de itens do quiz */
      quizItems: components["schemas"]["QuizItemResponseDTO"][];
      /**
       * @description Total de itens encontrados
       * @example 10
       */
      total: number;
    };
    UpdateQuizOptionDTO: {
      /**
       * @description Texto da opção
       * @example Opção A
       */
      text: string;
      /**
       * @description Indica se a opção é a correta
       * @example true
       */
      isCorrect: boolean;
      /**
       * @description Ordem da opção
       * @example 1
       */
      position: number;
      /**
       * @description ID da opção (pode ser usado para atualizar uma opção existente)
       * @example 1
       */
      id?: number;
    };
    UpdateQuizItemBodyDTO: {
      /**
       * @description Pergunta do item
       * @example Qual é a capital do Brasil?
       */
      question?: string;
      /**
       * @description Ordem do item no quiz
       * @example 1
       */
      position?: number;
      /**
       * @description Tempo limite em segundos
       * @example 30
       */
      timeLimit?: number;
      /**
       * @description Explicação da resposta
       * @example Brasília é a capital do Brasil desde 1960.
       */
      explanation?: string;
      /** @description Opções de resposta do item */
      options?: components["schemas"]["UpdateQuizOptionDTO"][];
    };
    CreateTaskBodyDTO: {
      /**
       * @description Nome da tarefa
       * @example Estudar matemática
       */
      name: string;
      /**
       * @description Descrição da tarefa
       * @example Revisar álgebra linear e cálculo diferencial
       */
      description?: string;
      /**
       * @description Status da tarefa
       * @example pending
       * @enum {string}
       */
      status: "pending" | "in_progress" | "completed" | "cancelled";
      /**
       * Format: date-time
       * @description Data de início da tarefa
       * @example 2024-01-15T10:00:00.000Z
       */
      startDate?: string;
      /**
       * Format: date-time
       * @description Data de término da tarefa
       * @example 2024-01-20T18:00:00.000Z
       */
      endDate?: string;
    };
    TaskResponseDTO: {
      /**
       * @description ID único da tarefa
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string;
      /**
       * @description Nome da tarefa
       * @example Estudar matemática
       */
      name: string;
      /**
       * @description Descrição da tarefa
       * @example Revisar álgebra linear e cálculo diferencial
       */
      description?: string;
      /**
       * @description Status da tarefa
       * @example pending
       * @enum {string}
       */
      status: "pending" | "in_progress" | "completed" | "cancelled";
      /**
       * Format: date-time
       * @description Data de início da tarefa
       * @example 2024-01-15T10:00:00.000Z
       */
      startDate?: string;
      /**
       * Format: date-time
       * @description Data de término da tarefa
       * @example 2024-01-20T18:00:00.000Z
       */
      endDate?: string;
      /**
       * Format: date-time
       * @description Data de criação do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Data da última atualização do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      updatedAt: string;
    };
    FindTaskResponseDTO: {
      /** @description Lista de tarefas */
      tasks: components["schemas"]["TaskResponseDTO"][];
      /**
       * @description Total de tarefas encontradas
       * @example 10
       */
      total: number;
    };
    UpdateTaskBodyDTO: {
      /**
       * @description Nome da tarefa
       * @example Estudar matemática
       */
      name?: string;
      /**
       * @description Descrição da tarefa
       * @example Revisar álgebra linear e cálculo diferencial
       */
      description?: string;
      /**
       * @description Status da tarefa
       * @example pending
       * @enum {string}
       */
      status?: "pending" | "in_progress" | "completed" | "cancelled";
      /**
       * Format: date-time
       * @description Data de início da tarefa
       * @example 2024-01-15T10:00:00.000Z
       */
      startDate?: string;
      /**
       * Format: date-time
       * @description Data de término da tarefa
       * @example 2024-01-20T18:00:00.000Z
       */
      endDate?: string;
    };
    CreateUserBodyDTO: {
      /**
       * @description Nome do usuário
       * @example João Silva
       */
      name: string;
      /**
       * @description E-mail do usuário
       * @example joao.silva@example.com
       */
      email: string;
      /**
       * @description Senha do usuário (deve conter pelo menos 1 maiúscula, 1 minúscula, 1 número e 1 caractere especial)
       * @example Senha@123
       */
      password: string;
      /**
       * @description Número de telefone do usuário
       * @example +55 11 98765-4321
       */
      phoneNumber?: string;
      /**
       * Format: date-time
       * @description Data de nascimento do usuário
       * @example 1990-01-15
       */
      birthdate?: string;
    };
    FindUserResponseDTO: {
      /** @description Lista de usuários */
      users: components["schemas"]["UserResponseDTO"][];
      /**
       * @description Total de usuários encontrados
       * @example 10
       */
      total: number;
    };
    UpdateUserBodyDTO: {
      /**
       * @description Nome do usuário
       * @example João Silva
       */
      name?: string;
      /**
       * @description Senha do usuário (deve conter pelo menos 1 maiúscula, 1 minúscula, 1 número e 1 caractere especial)
       * @example Senha@123
       */
      password?: string;
      /**
       * @description Número de telefone do usuário
       * @example +55 11 98765-4321
       */
      phoneNumber?: string;
      /**
       * Format: date-time
       * @description Data de nascimento do usuário
       * @example 1990-01-15
       */
      birthdate?: string;
    };
    CreateWhiteboardBodyDTO: {
      /**
       * @description Título do whiteboard
       * @example Brainstorming de Projeto
       */
      title: string;
      /** @description Dados do whiteboard em formato JSON */
      content: Record<string, never>;
    };
    WhiteboardResponseDTO: {
      /**
       * @description ID único do whiteboard
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string;
      /**
       * @description Título do whiteboard
       * @example Brainstorming de Projeto
       */
      title: string;
      /** @description Dados do whiteboard em formato JSON */
      content: Record<string, never>;
      /**
       * Format: date-time
       * @description Data de criação do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Data da última atualização do registro
       * @example 2024-01-15T10:30:00.000Z
       */
      updatedAt: string;
    };
    FindWhiteboardResponseDTO: {
      /** @description Lista de whiteboards */
      whiteboards: components["schemas"]["WhiteboardResponseDTO"][];
      /**
       * @description Total de whiteboards encontrados
       * @example 10
       */
      total: number;
    };
    UpdateWhiteboardBodyDTO: {
      /**
       * @description Título do whiteboard
       * @example Brainstorming de Projeto
       */
      title?: string;
      /** @description Dados do whiteboard em formato JSON */
      content?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginBodyDTO"];
      };
    };
    responses: {
      /** @description Login realizado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponseDTO"];
        };
      };
      /** @description Credenciais inválidas */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutBodyDTO"];
      };
    };
    responses: {
      /** @description Logout realizado com sucesso */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Token inválido */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokensBodyDTO"];
      };
    };
    responses: {
      /** @description Tokens renovados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefreshTokensResponseDTO"];
        };
      };
      /** @description Refresh token inválido */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GroupController_find: {
    parameters: {
      query?: {
        /** @description ID do grupo */
        id?: string;
        /** @description Nome do grupo */
        name?: string;
        /** @description Código de convite do grupo */
        inviteCode?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grupos retornados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindGroupResponseDTO"];
        };
      };
    };
  };
  GroupController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGroupBodyDTO"];
      };
    };
    responses: {
      /** @description Grupo criado com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupResponseDTO"];
        };
      };
    };
  };
  GroupController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do grupo */
        groupId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grupo encontrado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupResponseDTO"];
        };
      };
      /** @description Grupo não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GroupController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do grupo */
        groupId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grupo deletado com sucesso */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Apenas o dono do grupo pode deletar o grupo */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Grupo não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GroupController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do grupo */
        groupId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateGroupBodyDTO"];
      };
    };
    responses: {
      /** @description Grupo atualizado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupResponseDTO"];
        };
      };
      /** @description Membro comum não tem permissão para atualizar o grupo */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Grupo não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GroupController_resetInviteCode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do grupo */
        groupId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Código de convite resetado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupResponseDTO"];
        };
      };
      /** @description Apenas o dono do grupo pode resetar o código de convite */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Grupo não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GroupController_join: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinGroupBodyDTO"];
      };
    };
    responses: {
      /** @description Entrou no grupo com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupMemberResponseDTO"];
        };
      };
      /** @description Código de convite inválido */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Usuário já é membro do grupo */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GroupMemberController_find: {
    parameters: {
      query?: {
        /** @description Filtrar por role do membro */
        role?: "owner" | "admin" | "member";
        /** @description Filtrar por ID do usuário */
        userId?: number;
      };
      header?: never;
      path: {
        /** @description ID do grupo */
        groupId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Membros retornados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindGroupMembersResponseDTO"];
        };
      };
    };
  };
  GroupMemberController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do grupo */
        groupId: string;
        /** @description ID do membro */
        memberId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Membro encontrado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupMemberResponseDTO"];
        };
      };
      /** @description Membro não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GroupMemberController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do grupo */
        groupId: string;
        /** @description ID do membro */
        memberId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Membro removido com sucesso */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permissão negada para remover membro */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Membro não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GroupMemberController_changeRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do grupo */
        groupId: string;
        /** @description ID do membro */
        memberId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeMemberRoleBodyDTO"];
      };
    };
    responses: {
      /** @description Role alterado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupMemberResponseDTO"];
        };
      };
      /** @description Permissão negada para alterar role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Membro não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuizController_find: {
    parameters: {
      query?: {
        /** @description ID do quiz */
        id?: string;
        /** @description Título do quiz */
        title?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Quizzes retornados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindQuizResponseDTO"];
        };
      };
    };
  };
  QuizController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateQuizBodyDTO"];
      };
    };
    responses: {
      /** @description Quiz criado com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuizResponseDTO"];
        };
      };
    };
  };
  QuizController_findShared: {
    parameters: {
      query?: {
        /** @description ID do quiz */
        id?: string;
        /** @description Título do quiz */
        title?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Quizzes retornados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindQuizResponseDTO"];
        };
      };
    };
  };
  QuizController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do quiz */
        quizId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Quiz encontrado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuizResponseDTO"];
        };
      };
      /** @description Quiz não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuizController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do quiz */
        quizId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Quiz deletado com sucesso */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Quiz não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuizController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do quiz */
        quizId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateQuizBodyDTO"];
      };
    };
    responses: {
      /** @description Quiz atualizado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuizResponseDTO"];
        };
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Quiz não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuizItemController_find: {
    parameters: {
      query?: {
        /** @description ID do item */
        id?: number;
        /** @description Pergunta do item */
        question?: string;
      };
      header?: never;
      path: {
        /** @description ID do quiz */
        quizId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Itens retornados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindQuizItemResponseDTO"];
        };
      };
    };
  };
  QuizItemController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do quiz */
        quizId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateQuizItemBodyDTO"];
      };
    };
    responses: {
      /** @description Item criado com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuizItemResponseDTO"];
        };
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuizItemController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do quiz */
        quizId: string;
        /** @description ID do item do quiz */
        quizItemId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item encontrado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuizItemResponseDTO"];
        };
      };
      /** @description Item não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuizItemController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do quiz */
        quizId: string;
        /** @description ID do item do quiz */
        quizItemId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item deletado com sucesso */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Item não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  QuizItemController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do quiz */
        quizId: string;
        /** @description ID do item do quiz */
        quizItemId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateQuizItemBodyDTO"];
      };
    };
    responses: {
      /** @description Item atualizado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuizItemResponseDTO"];
        };
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Item não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_find: {
    parameters: {
      query?: {
        /** @description ID da tarefa */
        id?: string;
        /** @description Nome da tarefa */
        name?: string;
        /** @description Status da tarefa */
        status?: "pending" | "in_progress" | "completed" | "cancelled";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tarefas retornadas com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindTaskResponseDTO"];
        };
      };
    };
  };
  TaskController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTaskBodyDTO"];
      };
    };
    responses: {
      /** @description Tarefa criada com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponseDTO"];
        };
      };
    };
  };
  TaskController_findShared: {
    parameters: {
      query?: {
        /** @description ID da tarefa */
        id?: string;
        /** @description Nome da tarefa */
        name?: string;
        /** @description Status da tarefa */
        status?: "pending" | "in_progress" | "completed" | "cancelled";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tarefas retornadas com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindTaskResponseDTO"];
        };
      };
    };
  };
  TaskController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da tarefa */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tarefa encontrada */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponseDTO"];
        };
      };
      /** @description Tarefa não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da tarefa */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tarefa deletada com sucesso */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tarefa não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID da tarefa */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTaskBodyDTO"];
      };
    };
    responses: {
      /** @description Tarefa atualizada com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponseDTO"];
        };
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tarefa não encontrada */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_find: {
    parameters: {
      query?: {
        /** @description ID do usuário */
        id?: number;
        /** @description Nome do usuário */
        name?: string;
        /** @description E-mail do usuário */
        email?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Usuários retornados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindUserResponseDTO"];
        };
      };
    };
  };
  UserController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserBodyDTO"];
      };
    };
    responses: {
      /** @description Usuário criado com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDTO"];
        };
      };
      /** @description Email já está em uso */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do usuário */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Usuário encontrado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDTO"];
        };
      };
      /** @description Usuário não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do usuário */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Usuário deletado com sucesso */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Usuário não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do usuário */
        userId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserBodyDTO"];
      };
    };
    responses: {
      /** @description Usuário atualizado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDTO"];
        };
      };
      /** @description Usuário não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WhiteboardController_find: {
    parameters: {
      query?: {
        /** @description ID do whiteboard */
        id?: string;
        /** @description Título do whiteboard */
        title?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Whiteboards retornados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindWhiteboardResponseDTO"];
        };
      };
    };
  };
  WhiteboardController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWhiteboardBodyDTO"];
      };
    };
    responses: {
      /** @description Whiteboard criado com sucesso */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WhiteboardResponseDTO"];
        };
      };
    };
  };
  WhiteboardController_findShared: {
    parameters: {
      query?: {
        /** @description ID do whiteboard */
        id?: string;
        /** @description Título do whiteboard */
        title?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Whiteboards retornados com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindWhiteboardResponseDTO"];
        };
      };
    };
  };
  WhiteboardController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do whiteboard */
        whiteboardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Whiteboard encontrado */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WhiteboardResponseDTO"];
        };
      };
      /** @description Whiteboard não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WhiteboardController_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do whiteboard */
        whiteboardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Whiteboard deletado com sucesso */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Whiteboard não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WhiteboardController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description ID do whiteboard */
        whiteboardId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWhiteboardBodyDTO"];
      };
    };
    responses: {
      /** @description Whiteboard atualizado com sucesso */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WhiteboardResponseDTO"];
        };
      };
      /** @description Permissões insuficientes para acessar o recurso */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Whiteboard não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
